### ISSUE TITLE
Crash on example .xodr

### ISSUE THREAD

**Issue by EmmanuelMess** [liuyf5231/opendriveparser#3]
Example .xord files at http://www.opendrive.org/download.html not working: http://www.opendrive.org/tools/CulDeSac.xodr

**Comment by bigbigtree** [comment]
try : https://github.com/bigbigtree/opendriveparser

**Comment by EmmanuelMess** [comment]
> try : [bigbigtree/opendriveparser](https://github.com/bigbigtree/opendriveparser)

The project I was using this for ended long ago.
